from Graph import Graph


graph = Graph()
# graph =Graph()
graph.addNode("A")
graph.addNode("B")
graph.addNode("C")
graph.addNode("D")
graph.addNode("E")
graph.addNode("F")
graph.addNode("G")
graph.addNode("H")
graph.addNode("I")
graph.addNode("J")
graph.addNode("K")
graph.addNode("L")
graph.addNode("M")
graph.addNode("N")
graph.addNode("O")
graph.addNode("P")
graph.addNode("Q")
graph.addEdge("A", "B")
graph.addEdge("A","C")
graph.addEdge('B','D')
graph.addEdge('B', 'E')
graph.addEdge('C', 'F')
graph.addEdge('C', 'G')
graph.addEdge('G', 'J')
graph.addEdge('G', 'K')
graph.addEdge('K', 'Q')
graph.addEdge('E', 'H')
graph.addEdge('E', 'I')
graph.addEdge('H', 'L')
graph.addEdge('H', 'M')
graph.addEdge('H', 'N')
graph.addEdge('I', 'O')
graph.addEdge('O', 'P')
print(graph.dfs('A', 'J'))


# graph.print()
# print()
# for k, v in graph.edgesList.items():
#     print(k, "=>", v)
# graph.dfs('a', 'f')


graph2 = Graph()
graph2.addNode('a')
graph2.addNode('b')
graph2.addNode('c')
graph2.addNode('d')
graph2.addNode('e')
graph2.addNode('f')

graph2.addEdge('a', 'c')
graph2.addEdge('a', 'b')
# graph2.addEdge('a', 'f')
graph2.addEdge('b', 'c')
graph2.addEdge('b', 'd')
# graph2.addEdge('c', 'f')
# graph2.addEdge('d', 'f')
graph2.addEdge('d', 'e')
graph2.addEdge('b', 'c')
graph2.addEdge('e', 'f')

# graph2.djikstraSearch('a', 'f')